Repository Altair-05/CodeBrosPlatform, pull requests merged in 2025-07, with the labels that each got.

#16 docs: add Getting Started guide for new developers(Fixes #9)
  GETTING_STARTED.md
Labels: good first issue, GSSOC, level 1

#24 fix: Fixed the rendering of notification content.
  client/src/components/header.tsx
Labels: bug, GSSOC, level 2

#28 Create LICENSE
  LICENSE
Labels: documentation, good first issue, GSSOC, level 1
